---
title: "AF analysis"
author: "Nicholas Sunderland"
date: "2025-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# requirements ====
library(data.table)
library(R.utils)
library(survival)
library(survminer)
library(survivalAnalysis)
library(lubridate)
library(ggplot2)
library(broom)


# read the data ====
cohort   <- fread("/mnt/project/early_onset_af_data/cohort.tsv.gz")
outcomes <- fread("/mnt/project/early_onset_af_data/cohort_outcomes.tsv.gz")
#cohort   <- fread("/Users/xx20081/Downloads/fake_cohort.tsv.gz")
#outcomes <- fread("/Users/xx20081/Downloads/fake_cohort_outcomes.tsv.gz")

# clean the data.table factors ====
cohort[, `:=`(sex             = factor(sex, levels = c("female", "male")), 
              ethnicity_group = factor(ethnicity_group, levels = c("white", "black_or_black_british", "chinese", "asian_or_asian_british", "other_ethnic_group", "mixed")), 
              smoking_status  = factor(smoking_status, levels = c("never", "previous", "current")),
              alcohol_intake  = factor(alcohol_intake, levels = c("Daily or almost daily", "Three or four times a week", "Once or twice a week", "One to three times a month", "Special occasions only", "Never")),
              early_onset_af  = factor(fcase(is.na(early_onset_af), "No AF", 
                                             early_onset_af==FALSE, "AF age > 60", 
                                             early_onset_af==TRUE, "AF \u2264 60"), levels = c("No AF","AF age > 60","AF \u2264 60")))]
```

## AF diagnosis counts
```{r counts}
ggplot(cohort, aes(x = early_onset_af)) +
  geom_bar() +
  geom_text(
    stat = "count",
    aes(label = scales::comma(after_stat(count))),
    vjust = -0.3
  ) +
  scale_y_continuous(labels = scales::comma, name="Counts") +
  theme_minimal() +
  theme(
    panel.grid.major.x = element_blank(), 
    axis.title.x = element_blank()
  )
```

## AF age at first diagnosis
```{r age_onset}
ggplot(cohort[early_onset_af!="No AF"], aes(x = age_first_af, fill = early_onset_af)) +
  geom_histogram(bins = 30) +
  scale_x_continuous(name="Age at first diagnosis") +
  scale_y_continuous(labels = scales::comma, name="Counts") +
  theme_minimal() +
  theme(
    panel.grid.major.x = element_blank(), 
    legend.title = element_blank(), 
    legend.position = "top"
  ) +
  facet_wrap(~early_onset_af, scales="free")
```

## Survival - all-cause mortality
```{r survival, echo=FALSE}
# create survival table ====
surv_tbl <- tmerge(data1   = cohort[!is.na(af_first_date) & af_first_date > assessment_date & af_first_date < date_last_fu, ],
                   data2   = cohort[!is.na(af_first_date) & af_first_date > assessment_date & af_first_date < date_last_fu, ],
                   tstart  = 0,
                   tstop   = interval(af_first_date, date_last_fu) / dyears(1),
                   id      = eid,
                   dead    = event(interval(af_first_date, date_of_death) / dyears(1), as.integer(death)),
                   options = list(idname="eid"))

# plot KM curves ====
ggsurvplot(survfit(Surv(tstop, death) ~ early_onset_af, data = surv_tbl, id = eid),
           data = surv_tbl,
           risk.table = FALSE,
           conf.int = FALSE,
           cumcensor = FALSE,
           pval = FALSE, 
           #xlim = c(0, 12), 
           censor.shape = NA) #+
  #lims(y = c(0.6, 1))


hazard_ratios <- tidy(coxph(Surv(tstart, tstop, dead) ~ early_onset_af, data = surv_tbl, id = eid), exponentiate = TRUE, conf.int = TRUE)
kableExtra::kable(hazard_ratios)
```

## Survival - HF admission
```{r survival_hf, echo=FALSE}
# create survival table ====
surv_tbl <- tmerge(data1   = cohort[!is.na(af_first_date) & af_first_date > assessment_date & af_first_date < date_last_fu, ],
                   data2   = cohort[!is.na(af_first_date) & af_first_date > assessment_date & af_first_date < date_last_fu, ],
                   tstart  = 0,
                   tstop   = interval(af_first_date, date_last_fu) / dyears(1),
                   id      = eid,
                   dead    = event(interval(af_first_date, date_of_death) / dyears(1), as.integer(death)),
                   options = list(idname="eid"))

surv_tbl <- tmerge(data1   = surv_tbl,
                   data2   = (outcomes
                              [pheno=="heart_failure" & source=="hes"]
                              [cohort, af_first_date := i.af_first_date, on="eid"]
                              [date > af_first_date]
                              [, .SD[which.min(date)], by="eid"]
                             ),
                   id      = eid,
                   hf_adm  = event(interval(af_first_date, date) / dyears(1), as.integer(!is.na(pheno))),
                   options = list(idname="eid"))

# plot KM curves ====
ggsurvplot(survfit(Surv(tstop, hf_adm) ~ early_onset_af, data = surv_tbl, id = eid),
           data = surv_tbl,
           risk.table = FALSE,
           conf.int = FALSE,
           cumcensor = FALSE,
           pval = FALSE, 
           #xlim = c(0, 12), 
           censor.shape = NA) #+
  #lims(y = c(0.6, 1))


hazard_ratios <- tidy(coxph(Surv(tstart, tstop, hf_adm) ~ early_onset_af, data = surv_tbl, id = eid), exponentiate = TRUE, conf.int = TRUE)
kableExtra::kable(hazard_ratios)

# save & upload to project space
if (FALSE) {
  system("dx upload /home/rstudio-server/early_onset_af/scripts/af_analysis.html --path /early_onset_af_data/af_analysis.html")
}
```
